/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/execute_program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Program */
        post: operations["execute_program_execute_program_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** ApiAnthropicConfig */
        ApiAnthropicConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provider: "anthropic";
            /** Model */
            model?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key: string;
        };
        /** ApiOpenAIConfig */
        ApiOpenAIConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provider: "openai";
            /** Model */
            model?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key: string;
        };
        /** ApiThreadAssistantAction */
        ApiThreadAssistantAction: {
            /** Message */
            message?: string | null;
            /** Plan */
            plan?: string | null;
            /** Code */
            code?: string | null;
            /** Code Output */
            code_output?: string | null;
            /** Code Error */
            code_error?: string | null;
        };
        /** ApiThreadInteraction */
        ApiThreadInteraction: {
            user_message: components["schemas"]["ApiThreadUserMessage"];
            /** Assistant Actions */
            assistant_actions?: components["schemas"]["ApiThreadAssistantAction"][];
        };
        /** ApiThreadUserMessage */
        ApiThreadUserMessage: {
            /** Text */
            text: string;
        };
        /** DdnConfig */
        DdnConfig: {
            /**
             * Url
             * @description URL of the /sql endpoint on Hasura DDN
             */
            url: string;
            /**
             * Headers
             * @description HTTP headers that should be forwarded to DDN
             */
            headers?: {
                [key: string]: string;
            };
        };
        /** ExecuteRequest */
        ExecuteRequest: {
            /** Code */
            code: string;
            /**
             * Promptql Api Key
             * @deprecated
             */
            promptql_api_key?: string | null;
            /** Ai Primitives Llm */
            ai_primitives_llm: (components["schemas"]["HasuraLlmConfig"] | components["schemas"]["ApiOpenAIConfig"] | components["schemas"]["ApiAnthropicConfig"]) | null;
            ddn: components["schemas"]["DdnConfig"] | null;
            /** Artifacts */
            artifacts: (components["schemas"]["TextArtifact"] | components["schemas"]["TableArtifact"] | components["schemas"]["VisualizationArtifact"])[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HasuraLlmConfig */
        HasuraLlmConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            provider: "hasura";
        };
        /** LlmUsage */
        LlmUsage: {
            /**
             * Provider
             * @default unknown
             */
            provider: string;
            /**
             * Model
             * @default unknown
             */
            model: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** PromptQlExecutionResult */
        PromptQlExecutionResult: {
            /** Output */
            output: string;
            /** Error */
            error: string | null;
            /** Accessed Artifact Ids */
            accessed_artifact_ids: string[];
            /** Modified Artifacts */
            modified_artifacts: (components["schemas"]["TextArtifact"] | components["schemas"]["TableArtifact"] | components["schemas"]["VisualizationArtifact"])[];
            /** Llm Usages */
            llm_usages: components["schemas"]["LlmUsage"][];
        };
        /** QueryRequest */
        QueryRequest: {
            /**
             * Version
             * @constant
             */
            version: "v1";
            /**
             * Promptql Api Key
             * @deprecated
             */
            promptql_api_key?: string | null;
            /** Llm */
            llm?: components["schemas"]["HasuraLlmConfig"] | components["schemas"]["ApiOpenAIConfig"] | components["schemas"]["ApiAnthropicConfig"];
            /** Ai Primitives Llm */
            ai_primitives_llm?: (components["schemas"]["HasuraLlmConfig"] | components["schemas"]["ApiOpenAIConfig"] | components["schemas"]["ApiAnthropicConfig"]) | null;
            ddn: components["schemas"]["DdnConfig"];
            /** Artifacts */
            artifacts?: (components["schemas"]["TextArtifact"] | components["schemas"]["TableArtifact"] | components["schemas"]["VisualizationArtifact"])[];
            /** System Instructions */
            system_instructions?: string | null;
            /**
             * Timezone
             * @description An IANA timezone used to interpret queries that implicitly require timezones
             */
            timezone: string;
            /** Interactions */
            interactions: components["schemas"]["ApiThreadInteraction"][];
            /** Stream */
            stream: boolean;
        };
        /** QueryResponse */
        QueryResponse: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Assistant Actions */
            assistant_actions: components["schemas"]["ApiThreadAssistantAction"][];
            /**
             * Modified Artifacts
             * @description List of artifacts created or updated in this request. May contain duplicate artifact identifiers.
             */
            modified_artifacts: (components["schemas"]["TextArtifact"] | components["schemas"]["TableArtifact"] | components["schemas"]["VisualizationArtifact"])[];
        };
        /** TableArtifact */
        TableArtifact: {
            /** Identifier */
            identifier: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "table";
            /**
             * Data
             * @description Table data as a list of objects, with the object keys being column names
             */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** TextArtifact */
        TextArtifact: {
            /** Identifier */
            identifier: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "text";
            /** Data */
            data: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VisualizationArtifact */
        VisualizationArtifact: {
            /** Identifier */
            identifier: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "visualization";
            /** @description Visualization data containing HTML and visualization data */
            data: components["schemas"]["VisualizationArtifactData"];
        };
        /**
         * VisualizationArtifactData
         * @description Data structure for visualization artifacts containing HTML and associated data.
         *
         *     Attributes:
         *         html: The HTML markup for rendering the visualization
         *         visualization_data: The underlying data used to generate the visualization
         */
        VisualizationArtifactData: {
            /** Html */
            html: string;
            /** Visualization Data */
            visualization_data: unknown;
        };
        QueryResponseChunk: components["schemas"]["ThreadMetadataChunk"] | components["schemas"]["AssistantActionChunk"] | components["schemas"]["ArtifactUpdateChunk"] | components["schemas"]["ErrorChunk"];
        /** ArtifactUpdateChunk */
        ArtifactUpdateChunk: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "artifact_update_chunk";
            /** Artifact */
            artifact: components["schemas"]["TextArtifact"] | components["schemas"]["TableArtifact"] | components["schemas"]["VisualizationArtifact"];
        };
        /** AssistantActionChunk */
        AssistantActionChunk: {
            /**
             * Message
             * @default null
             */
            message: string | null;
            /**
             * Plan
             * @default null
             */
            plan: string | null;
            /**
             * Code
             * @default null
             */
            code: string | null;
            /**
             * Code Output
             * @default null
             */
            code_output: string | null;
            /**
             * Code Error
             * @default null
             */
            code_error: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assistant_action_chunk";
            /** Index */
            index: number;
        };
        /** ErrorChunk */
        ErrorChunk: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error_chunk";
            /** Error */
            error: string;
        };
        /** ThreadMetadataChunk */
        ThreadMetadataChunk: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "thread_metadata_chunk";
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type ApiAnthropicConfig = components['schemas']['ApiAnthropicConfig'];
export type ApiOpenAiConfig = components['schemas']['ApiOpenAIConfig'];
export type ApiThreadAssistantAction = components['schemas']['ApiThreadAssistantAction'];
export type ApiThreadInteraction = components['schemas']['ApiThreadInteraction'];
export type ApiThreadUserMessage = components['schemas']['ApiThreadUserMessage'];
export type DdnConfig = components['schemas']['DdnConfig'];
export type ExecuteRequest = components['schemas']['ExecuteRequest'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type HasuraLlmConfig = components['schemas']['HasuraLlmConfig'];
export type LlmUsage = components['schemas']['LlmUsage'];
export type PromptQlExecutionResult = components['schemas']['PromptQlExecutionResult'];
export type QueryRequest = components['schemas']['QueryRequest'];
export type QueryResponse = components['schemas']['QueryResponse'];
export type TableArtifact = components['schemas']['TableArtifact'];
export type TextArtifact = components['schemas']['TextArtifact'];
export type ValidationError = components['schemas']['ValidationError'];
export type VisualizationArtifact = components['schemas']['VisualizationArtifact'];
export type VisualizationArtifactData = components['schemas']['VisualizationArtifactData'];
export type QueryResponseChunk = components['schemas']['QueryResponseChunk'];
export type ArtifactUpdateChunk = components['schemas']['ArtifactUpdateChunk'];
export type AssistantActionChunk = components['schemas']['AssistantActionChunk'];
export type ErrorChunk = components['schemas']['ErrorChunk'];
export type ThreadMetadataChunk = components['schemas']['ThreadMetadataChunk'];
export type $defs = Record<string, never>;
export interface operations {
    execute_program_execute_program_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptQlExecutionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Either a JSON response (QueryResponse object) or a stream of Server-Sent Events (SSE) (QueryResponseChunk objects) depending on whether the 'stream' parameter was set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                    /** @example data: {"message":"Let me try to store an artifact","plan":null,"code":null,"code_output":null,"code_error":null,"type":"assistant_action_chunk","index":0}
                     *
                     *     data: {"message":null,"plan":"- Store an artifact with sample data","code":null,"code_output":null,"code_error":null,"type":"assistant_action_chunk","index":0}
                     *
                     *     data: {"message":null,"plan":null,"code":"executor.store_artitfact('test', 'Test artifact', 'table', [{'foo':'bar'}])","code_output":null,"code_error":null,"type":"assistant_action_chunk","index":0}
                     *
                     *     data: {"message":null,"plan":null,"code":null,"code_output":"Artifact stored","code_error":null,"type":"assistant_action_chunk","index":0}
                     *
                     *     data: {"type":"artifact_update_chunk","artifact":{"identifier":"test","title":"Test Artifact","artifact_type":"table","data":[{"foo":"bar"}]}}
                     *
                     *     data: {"message":"Your artifact is <artifact","plan":null,"code":null,"code_output":null,"code_error":null,"type":"assistant_action_chunk","index":1}
                     *
                     *     data: {"message":" identifier='test'/>","plan":null,"code":null,"code_output":null,"code_error":null,"type":"assistant_action_chunk","index":1}
                     *
                     *      */
                    "text/event-stream": components["schemas"]["QueryResponseChunk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
