name: Publish Package to npmjs
on:
  push:
    tags:
      - v*
jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  publish:
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: rm package-lock.json && npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
