name: Unit tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: |
          npm ci
          npm i -D @biomejs/biome@1.9.4
      - run: npm run lint:fix
      - run: npm run test