name: Unit tests

on:
  workflow_call:
  pull_request:
    paths:
      - "src/**.ts"
      - "*.json"
      - "vite.config.ts"
      - ".github/workflows/*.yaml"

  push:
    branches:
      - "main"
    paths:
      - "src/**.ts"
      - "*.json"
      - "vite.config.ts"
      - ".github/workflows/*.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: rm package-lock.json && npm install
      - run: npm run lint:fix
      - run: npm run test