name: Lint, Tests and Publish

on:
  workflow_call:
  pull_request:
    paths:
      - "src/**.ts"
      - "*.json"
      - "vite.config.ts"
      - ".github/workflows/*.yaml"

  push:
    branches:
      - "main"
    tags:
      - v*
    paths:
      - "src/**.ts"
      - "*.json"
      - "vite.config.ts"
      - ".github/workflows/*.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: rm package-lock.json && npm install
      - run: npm run lint:fix
      - run: npm run build
      - run: npm run test:coverage
        env:
          PROMPTQL_API_KEY: ${{ secrets.PROMPTQL_API_KEY }}
          HASURA_DDN_BASE_URL: ${{ secrets.HASURA_DDN_BASE_URL }}
          DDN_AUTH_TOKEN: ${{ secrets.DDN_AUTH_TOKEN }}
          HASURA_DDN_BUILD_VERSION: ${{ secrets.HASURA_DDN_BUILD_VERSION }}
      - name: 'Report Coverage'
        if: ${{ github.event_name == 'pull_request' }}
        uses:  davelosert/vitest-coverage-report-action@v2

  publish:
    runs-on: ubuntu-latest
    needs: [lint-test]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: rm package-lock.json && npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get version from tag
        id: get-version
        run: |
          echo "tagged_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: create a draft release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: v${{ steps.get-version.outputs.tagged_version }}